### ISSUE TITLE
Environments?

### ISSUE THREAD

**Issue by et304383** [daidokoro/qaz#31]
I'm quite sure after reading the docs how I'm supposed to handle environments.

If I want to have a different, say, VPC CIDR block for dev vs stage, how do I handle this?

Are stacks the "environments" ?

If that's the case, how do I template a CIDR block value based on the environment/stack?  All the examples I see have hard coded references to `.<stack name>.cidr`

**Comment by daidokoro** [comment]
Hi,

I can see the confusion, I need to update the Docs a bit as some changes were made to address this a while ago.

You can use a single template and dynamically switch values using the `{{ .stack }}` keyword. `.stack` will always evaluate the values of the stack calling the template.

_config.yaml_
```yaml
project: qaz-test

stacks:
  dev:
    source: template.yaml
    cf:
      cidr: 10.10.10.0/24

  staging:
    source: template.yaml
    cf:
      cidr: 192.168.10.0/24
```
_template.yaml_
```yaml
Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: {{ .stack.cidr }}
```

Given the config and template above, if I generate the templates, they will have difference values.

```
$ qaz generate dev
```
Output:
```yaml

Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.10.10.0/24
```

```
$ qaz generate staging
```
Output:
```yaml
Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 192.168.10.0/24
```

The `.stack` template keyword can be used in place of the stack name, in fact, I recommend it. This way templates are not bound to a single stack. so `<stack name>.cidr` becomes `.stack.cidr`

Thanks for using Qaz and let me know if this helps.

**Comment by et304383** [comment]
Ahh this value would have been immensely useful to know about.  :)

Is this the same as ".name" though?  I tried doing `.name.cidr` but that didn't work.  It actually silently crashed and spit out the template up until the first occurrence of that substitution string.

**Comment by daidokoro** [comment]
No prob.

`{{ .name }}` returns the name of the Stack currently calling the template, it's handy if you want to do things in your template based on the name of the stack calling it.

For example, let's say I want my Dev env to have an extra VPC. I could do..

_template.yaml_
```yaml
Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: {{ .stack.cidr }}

  {{ if eq  .name "dev" }}
    vpc2:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: {{ .stack.cidr }}
  {{ end }}
```

So now if I generate template for dev, I'll get.

```yaml
Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.10.10.0/24

  
  vpc2:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.10.10.0/24
```

While generating the same of staging will give:

```yaml
Resources:
  vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 192.168.10.0/24

```

Apologies for Docs not being up to date. Been fairly busy lately but I'll see if I can get some useful info and vidz added soon.

Let me know if you have any more questions.
