### ISSUE TITLE
support for notification-arns in qaz

### ISSUE THREAD

**Issue by jtuller** [daidokoro/qaz#38]
It would be nice to be able to set the notification arns for cloudformation create / update events. with the aws cli it's as easy as specifying some ARNs behind the --notification-arns like so:

https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
```
--notification-arns (list)

The Simple Notification Service (SNS) topic ARNs to publish stack related events. You can find your SNS topic ARNs using the SNS console or your Command Line Interface (CLI).
Syntax:

"string" "string" ...
```

Would you be open to this? I'm thinking it should be in the config.yml as a property of the stack, something like:

```
region: us-east-1
project: my-project

stacks:
 my-stack:
    source: ./cloud-formation.yml
    parameters:
      - ParamOne: some-value
      - ParamTwo: anotherValue
    notification-arns:
      - arn:aws:sns:us-east-1:123456789012:MyCloudFormationEventSNSTopic
      - arn:aws:sns:us-east-1:123456789012:MyOtherCloudFormationEventSNSTopic
```

If there is already support for this I did not notice it in the documentation.
