### ISSUE TITLE
Handling Stack Parameters

### ISSUE THREAD

**Issue by daidokoro** [daidokoro/qaz#8]
Initially didn't consider this as Qaz is able to write values from the config directly their respective locations in the template. However, given the issue of sensitive data, for eg. DB passwords and such. I believe I need to support parametrisation so the `NoEcho` Cloudformation flag can be implemented when needed.

I'm thinking a new keyword in config. So stack config would look like this:

```yaml
stacks:
  rds:
    depends_on:
       - vpc
    
    parameters:
       - param_name: param_value

    cf:
      yourvalues: value
```
